apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ai-service-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: ai-service
  namespaceSelector:
    matchNames:
      - tactic-dev
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
