name: tactic-runners

services:
  github-runner-1:
    image: myoung34/github-runner:latest
    container_name: tactic-github-runner-1
    restart: unless-stopped
    environment:
      REPO_URL: ${GITHUB_RUNNER_REPO_URL}
      RUNNER_TOKEN: ${GITHUB_RUNNER_TOKEN}
      RUNNER_NAME_PREFIX: tactic-runner-1
      RANDOM_RUNNER_SUFFIX: "true"
      RUNNER_SCOPE: repo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - tactic-platform

  github-runner-2:
    image: myoung34/github-runner:latest
    container_name: tactic-github-runner-2
    restart: unless-stopped
    environment:
      REPO_URL: ${GITHUB_RUNNER_REPO_URL}
      RUNNER_TOKEN: ${GITHUB_RUNNER_TOKEN}
      RUNNER_NAME_PREFIX: tactic-runner-2
      RANDOM_RUNNER_SUFFIX: "true"
      RUNNER_SCOPE: repo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - tactic-platform

  github-runner-3:
    image: myoung34/github-runner:latest
    container_name: tactic-github-runner-3
    restart: unless-stopped
    environment:
      REPO_URL: ${GITHUB_RUNNER_REPO_URL}
      RUNNER_TOKEN: ${GITHUB_RUNNER_TOKEN}
      RUNNER_NAME_PREFIX: tactic-runner-3
      RANDOM_RUNNER_SUFFIX: "true"
      RUNNER_SCOPE: repo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - tactic-platform

networks:
  tactic-platform:
    external: true
    name: tactic-platform_platform