apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - secret-template.yaml
  - backend-blue.yaml
  - backend-green.yaml
  - frontend-blue.yaml
  - frontend-green.yaml
  - ai-blue.yaml
  - ai-green.yaml
  - services.yaml
  - ingress.yaml
