apiVersion: v1
kind: Secret
metadata:
  name: tactic-secrets
  namespace: tactic-dev
type: Opaque
stringData:
  APP_KEY: "base64:replace_me"
  JWT_SECRET: "replace_me"
  DB_PASSWORD: "replace_me"
  MAIL_PASSWORD: "replace_me"
  REVERB_APP_KEY: "replace_me"
  REVERB_APP_SECRET: "replace_me"
